HPOS - fatal error when trying to create a manual order in WC
krokedil/klarna-order-management-for-woocommerce pull request #106
Opened 2023-09-13 12:52 UTC by mntzrr

Fixed a critical order when the merchant creates a new order while HPOS is enabled.

Related task: https://app.clickup.com/t/865d18nj6

2023-09-13 12:52 UTC, mntzrr commented
Task linked: [CU-865d18nj6 HPOS - fatal error when trying to create a manual order in WC](https://app.clickup.com/t/865d18nj6)

2023-09-15 06:46 UTC, MichaelBengtsson requested changes
Looks good, but please look over the PHPCS issues and solve them if possible

2023-09-15 06:46 UTC, MichaelBengtsson commented on classes/class-wc-klarna-meta-box.php
>  		if ( in_array( $post_type, array( 'woocommerce_page_wc-orders', 'shop_order' ) ) ) {
Add true as the third argument to fix the PHPCS issue to the in_array check

2023-09-15 06:46 UTC, MichaelBengtsson commented on includes/klarna-order-management-functions.php
> +//phpcs:ignore
What is this ignore for? Can you add a more specific rule for it to ignore with a description of why?

2023-09-20 06:19 UTC, MichaelBengtsson approved these changes

2023-09-20 06:19 UTC, merged